/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cqggsqwulhujgtqweovv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxZ2dzcXd1bGh1amd0cXdlb3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1Njk2MTYsImV4cCI6MjA4OTE0NTYxNn0.d6YuSmyREfL2cL8rofKrgZw-ZHw3qFPzUq9I-lLFsHk"